from pathlib import Path
import json
import subprocess

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "science" / "114" / "data.js"
OUT = ROOT / "science" / "114-summer"
SELECTED = [
    1, 2, 3, 4, 7, 8, 11, 12, 14, 17,
    19, 20, 21, 22, 24, 26, 27, 28, 29, 30,
    32, 34, 35, 36, 38, 40, 43, 44, 45, 46,
]
GRADE1 = {3, 7, 8, 12, 20, 22, 24, 27, 30, 34, 35, 36, 45, 46}
GRADE2 = set(SELECTED) - GRADE1
EXCLUDED_G9 = sorted(set(range(1, 51)) - set(SELECTED))


def load_quiz():
    src_path = str(SRC).replace("\\", "/")
    script = f"""
global.window={{}};
require({json.dumps(src_path)});
console.log(JSON.stringify(window.QUIZ));
"""
    tmp = ROOT / ".tmp_dump_science114.js"
    tmp.write_text(script, encoding="utf-8")
    try:
        out = subprocess.check_output(["node", str(tmp)], cwd=str(ROOT), text=True, encoding="utf-8")
    finally:
        tmp.unlink(missing_ok=True)
    return json.loads(out)


def main():
    quiz = load_quiz()
    qmap = {q["no"]: q for q in quiz["questions"]}
    missing = [n for n in SELECTED if n not in qmap]
    if missing:
        raise SystemExit(f"Missing questions: {missing}")
    questions = []
    for n in SELECTED:
        q = dict(qmap[n])
        q["images"] = ["../114/" + img for img in q.get("images", [])]
        q["summerScope"] = "國一生物／探究" if n in GRADE1 else "國二理化／探究"
        q["excludedNote"] = "暑期版保留題：排除國三理化、地科與天文後的國一國二範圍"
        questions.append(q)
    out_quiz = {
        "id": "cap-114-science-summer",
        "siteTitle": "會考複習自學平台",
        "title": "114年自然科會考暑期版（國一＋國二範圍）",
        "subject": "自然科暑期版",
        "grade": "國一國二複習",
        "perScore": 2,
        "totalScore": len(questions) * 2,
        "sourceLabel": "114年國中教育會考自然科官方公開試題；暑期版選入國一、國二範圍並排除國三理化／地科／天文",
        "sourceUrl": "https://cap.rcpet.edu.tw/",
        "description": "暑期版精選 30 題：保留 114 自然會考中適合國一、國二先複習的生物、基礎理化與探究素養題，排除國三力學／電學／電磁／簡單機械、地科與天文題。",
        "summerScope": {
            "selected": SELECTED,
            "grade1": sorted(GRADE1),
            "grade2": sorted(GRADE2),
            "excludedGrade9Related": EXCLUDED_G9,
            "rule": "保留國一＋國二；排除國三理化、國三地科、天文。"
        },
        "questions": questions,
    }
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "data.js").write_text(
        "/* 114 CAP Science summer self-study quiz data. Generated by build_science114_summer.py. */\n"
        "window.CLOUD = window.CLOUD || { enabled: false, teacherEmail: \"\", config: {} };\n"
        "window.QUIZ = " + json.dumps(out_quiz, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT/'data.js'} with {len(questions)} questions; excluded {len(EXCLUDED_G9)} grade-9-related questions")


if __name__ == "__main__":
    main()
